### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by Ching-Huang**
I am comet.
Thx~

### CODE REVIEW

**Comment by cwpeng** [comment]
I need your online URLs for testing.

**Comment by Ching-Huang** [comment]
http://13.215.5.23:3000/

sorry~ I forgot it.

**Comment by cwpeng** [comment]
1. Aspect ratio of images should keep the same as original ones in any size device.
2. Text in the top-right will break into 2 lines in some devices.
3. Content in navigator, key visual section, and attraction list should align left and right with each other in larger devices. (>1200px)
4. Search icon is fly out from search box in larger devices.

未命名-2
未命名-6

**Comment by Ching-Huang** [comment]
Hope that  nice to hear from your good news.
Thx~
http://13.215.5.23:3000/

**Comment by cwpeng** [comment]
1. No fix.
2. OK.
3. No fix.
4. OK.

未命名-6
未命名-7

**Comment by Ching-Huang** [comment]
plz test again , thx~
http://13.215.5.23:3000/

**Review by cwpeng — APPROVED** [review]
OK. Done. Keep Going.

**Pull request merged**
